# Generated by Django 5.2.6 on 2025-09-21 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BingoCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.CharField(max_length=3, unique=True)),
                ('numbers', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('game_count', models.IntegerField(blank=True, null=True)),
                ('package_type', models.CharField(choices=[('fixed', 'Fixed Count'), ('unlimited', 'Monthly Unlimited')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='SerialKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('activated', models.BooleanField(default=False)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bingo.package')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wager_amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('played_at', models.DateTimeField(auto_now_add=True)),
                ('is_winner', models.BooleanField(default=False)),
                ('bingo_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bingo.bingocard')),
                ('serial_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bingo.serialkey')),
            ],
        ),
        migrations.CreateModel(
            name='VerificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('called_numbers', models.JSONField()),
                ('winning_lines', models.JSONField()),
                ('is_winner', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('round_hash', models.CharField(db_index=True, default='', max_length=64)),
                ('claim_index', models.IntegerField(default=0)),
                ('assigned_rank', models.IntegerField(blank=True, null=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='bingo.bingocard')),
            ],
        ),
    ]
