# Generated by Django 5.2.6 on 2025-09-21 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serialkey',
            name='generated_cards',
            field=models.IntegerField(default=0),
        ),
    ]
