"""
Django settings for src project.

Generated by 'django-admin startproject' using Django 5.2.6.
Docs:
- Settings overview: https://docs.djangoproject.com/en/5.2/ref/settings/
- i18n: https://docs.djangoproject.com/en/5.2/topics/i18n/
"""

from pathlib import Path
from django.utils.translation import gettext_lazy as _

# ---------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------
BASE_DIR = Path(__file__).resolve().parent.parent

# ---------------------------------------------------------------------
# Core / Security
# ---------------------------------------------------------------------
SECRET_KEY = 'django-insecure-l9a12lciu0t29))oyb!q+x#x20mpbhqc^m2rh=280k%dacu-#l'  # change in prod
DEBUG = True
ALLOWED_HOSTS: list[str] = []  # set hosts in prod

# ---------------------------------------------------------------------
# Applications
# ---------------------------------------------------------------------
INSTALLED_APPS = [
    # Django contrib
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Local apps
    'bingo',
]

# ---------------------------------------------------------------------
# Middleware (LocaleMiddleware must be after SessionMiddleware and before CommonMiddleware)
# ---------------------------------------------------------------------
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',   # <- correct position
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# ---------------------------------------------------------------------
# URLs / WSGI
# ---------------------------------------------------------------------
ROOT_URLCONF = 'src.urls'
WSGI_APPLICATION = 'src.wsgi.application'

# ---------------------------------------------------------------------
# Templates
#   - Add i18n context processor so language helpers are available in templates
# ---------------------------------------------------------------------
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],  # add project-level template dirs if you have them
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.template.context_processors.i18n',   # <- important for i18n in templates
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# ---------------------------------------------------------------------
# Database (SQLite for dev)
# ---------------------------------------------------------------------
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# ---------------------------------------------------------------------
# Password validation
# ---------------------------------------------------------------------
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# ---------------------------------------------------------------------
# Internationalization (i18n / l10n / tz)
#   - USE_L10N is removed in Django 5; formatting now follows the current locale automatically.
#   - Keep LANGUAGE_CODE simple ('en'); URL language prefixes are handled by i18n_patterns.
# ---------------------------------------------------------------------
LANGUAGE_CODE = 'en'
TIME_ZONE = 'UTC'                      # or 'Africa/Addis_Ababa' if you prefer local time
USE_I18N = True
USE_TZ = True

# Available languages (lazy-marked for admin/UI readability)
LANGUAGES = [
    ('en', _('English')),
    ('am', _('Amharic')),
]

# Where your .po/.mo files live (manage.py makemessages/compilemessages)
LOCALE_PATHS = [
    BASE_DIR / 'locale',
]

# Optional: cookie settings (defaults shown for clarity; tweak in prod if needed)
LANGUAGE_COOKIE_NAME = 'django_language'
# LANGUAGE_COOKIE_SECURE = True          # enable in HTTPS production
# LANGUAGE_COOKIE_SAMESITE = 'Lax'
# LANGUAGE_COOKIE_HTTPONLY = False

# ---------------------------------------------------------------------
# Static files
# ---------------------------------------------------------------------
STATIC_URL = '/static/'
# STATIC_ROOT = BASE_DIR / 'staticfiles'  # set in production for collectstatic
# STATICFILES_DIRS = [BASE_DIR / 'static']  # if you have extra static dirs in dev

# ---------------------------------------------------------------------
# Defaults
# ---------------------------------------------------------------------
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
